### ISSUE TITLE
Dockerize The Detection System Program

### ISSUE THREAD

**Issue by elle-Bee** [elle-Bee/Road-Lane-Detection-System#1]
### Description:

**Overview:**
The Python-based road lane detection system, powered by OpenCV, needs to be containerized using Docker. This will simplify deployment, eliminate environmental discrepancies, and enhance the overall portability of the system.

**Goal:**
The objective of this issue is to create a Docker image that encapsulates the road lane detection system along with its dependencies, ensuring seamless deployment across different environments.

### Tasks:

1. **Create Dockerfile:**
   -  Write a Dockerfile to define the Docker image.
   - Include OpenCV and any other necessary dependencies.
   - Set up the appropriate base image.

2. **Build and Test:**
   - Ensure the Dockerfile builds without errors.
   - Test the Docker image locally to verify that the road lane detection system works seamlessly within the container.

3. **Documentation:**
   - Update README with instructions on building and running the Dockerized road lane detection system.
   - Provide examples and sample commands for deploying the system in a Docker container.

### Acceptance Criteria:

- The Dockerfile is created, and the Docker image can be built successfully.
- The Dockerized road lane detection system runs without errors in a local environment.
- The README is updated with clear instructions for building and running the Docker image.

**Comment by harshau007** [comment]
Hey @elle-Bee, Since program takes inputs from path i don't think it would work for input and we have to change it to arguments based if we have to containerize the program

**Comment by elle-Bee** [comment]
@harshau007 we can simply mount volumes in the dockerfile and then in the main program amke the changes for the same to work.

**Comment by harshau007** [comment]
Okkk I will look into it

**Comment by Dhruv-Pattel** [comment]
hello, @elle-Bee! I am interested in contributing to this issue. Could you please assign it to me?

**Comment by elle-Bee** [comment]
Hay @Dhruv-Pattel I'll assign it to you once the coding period for KWOC starts (assuming  you have registered)

**Comment by elle-Bee** [comment]
Hey @Dhruv-Pattel are you still interested in this issue?

**Comment by Dhruv-Pattel** [comment]
Yes @elle-Bee . I'm working on it.

**Comment by elle-Bee** [comment]
Great, I'll assign it to you then!

**Comment by asmitdeb** [comment]
Hi! Can I work on this issue if it is up for grabs? @elle-Bee

**Comment by elle-Bee** [comment]
Hey @asmitdeb , @Dhruv-Pattel is already assigned with this issue
