### ISSUE TITLE
CI/CD: Format Python Code

### ISSUE THREAD

**Issue by elle-Bee** [elle-Bee/Road-Lane-Detection-System#3]
### Context?
GitHub workflows can be used to automate some tasks which would generally take time doing manually and are better automated.

### What to do?
Create workflows for some common scenarios like:

- Checking whether code builds successfully in pull requests and when PRs are merged in master branch. See - #4 
- Running tools like Black and Pylint in PRs to keep clean code. See - #5 

### Resources:
- A guide on GitHub actions and workflows - https://docs.github.com/en/actions
- GitHub workflows syntax guide - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
- Python formatting tools - [Black](https://github.com/psf/black) [Pylint](https://github.com/pylint-dev/pylint)

### NOTE
Try picking any one of the scenario and comment on the respective issues to show your interest. We'll assign it to you.

**Comment by harshau007** [comment]
Hey @elle-Bee, I would like to work on this issue.

**Comment by elle-Bee** [comment]
Hey @harshau007 are you contributing through KWOC?

**Comment by harshau007** [comment]
> Hey @harshau007 are you contributing through KWOC?

Yes

**Comment by elle-Bee** [comment]
Cool, I'll assign it to you once the coding period officially starts. :)

**Comment by harshau007** [comment]
Okk 👍
