### ISSUE TITLE
GitHub Actions for building code

### ISSUE THREAD

**Issue by elle-Bee** [elle-Bee/Road-Lane-Detection-System#4]
See #3

**Comment by asmitdeb** [comment]
Hi, I would like to work on this issue, please assign it to me

**Comment by elle-Bee** [comment]
hey @asmitdeb I'll assign it to you once the coding period for KWOC starts

**Comment by asmitdeb** [comment]
Just a reminder to assign this to me on 9th Dec, @elle-Bee

**Comment by elle-Bee** [comment]
Hey @asmitdeb go ahead!
