### ISSUE TITLE
Add workflows for running Black and Pylint in PRs

### ISSUE THREAD

**Issue by elle-Bee** [elle-Bee/Road-Lane-Detection-System#5]
See #3

The workflows should be written in such a way that Black formats the code first and then pylint is run

**Comment by harshagr70** [comment]
hey !! @elle-Bee i would like to work on this issue .

**Comment by elle-Bee** [comment]
Hey @harshagr70 I'll assign to you once the coding period for KWOC starts (assuming you have registered through it)

**Comment by harshagr70** [comment]
Sure @elle-Bee Im happy to hear back from you !!! , I have registered and will wait for you to respond further 😀

**Comment by elle-Bee** [comment]
Hey @harshagr70 are you still interested in this issue?

**Comment by kausthub-kannan** [comment]
Hello, @elle-Bee I would like to work on this issue, I have registered for KWoC

**Comment by elle-Bee** [comment]
Go ahead @kausthub-kannan !

**Comment by harshagr70** [comment]
> Hey @harshagr70 are you still interested in this issue?

yess @elle-Bee was waiting to hear back from you !!

**Comment by elle-Bee** [comment]
Hey @harshagr70 maybe you can work in with @kausthub-kannan ? There is some issue regarding the workflow not triggering. Can you have a look #8 ?

**Comment by harshagr70** [comment]
> Hey @harshagr70 maybe you can work in with @kausthub-kannan ? There is some issue regarding the workflow not triggering. Can you have a look #8 ?

sure  !! @elle-Bee
