### ISSUE TITLE
codeofconduct,contributong.md,security

### ISSUE THREAD

**Issue by pinak22dhir** [elle-Bee/Road-Lane-Detection-System#6]
can u assign this to me?

**Comment by elle-Bee** [comment]
Hi @pinak22dhir 
Thank you for your interest in contributing to our project! I appreciate your willingness to help. Before we proceed, could you please provide more details about the specific area you would like to work on? This will help me better understand your expertise and assign the issue accordingly.

**Comment by pinak22dhir** [comment]
Our Pledge
In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to make participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

Our Standards
Examples of behaviour that contributes to a positive environment for our community include:

Demonstrating empathy and kindness toward other people
Being respectful of differing opinions, viewpoints, and experiences
Giving and gracefully accepting constructive feedback
Accepting responsibility and apologising to those affected by our mistakes, and learning from the experience
Focusing on what is best not just for us as individuals, but for the overall community
Examples of unacceptable behaviour include:

The use of sexualised language or imagery, and sexual attention or advances
Trolling, insulting or derogatory comments, and personal or political attacks
Public or private harassment
Publishing others' private information, such as a physical or email address, without their explicit permission
Other conduct which could reasonably be considered inappropriate in a professional setting
Our Responsibilities
Project maintainers are responsible for clarifying and enforcing our standards of acceptable behaviour and will take appropriate and fair corrective action in response to any instances of unacceptable behaviour.

Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviours that they deem inappropriate, threatening, offensive, or harmful.

Scope
This Code of Conduct applies within all community spaces, and also applies when an individual is officially representing the community in public spaces. Examples of representing our community include using an official e-mail address, posting via an official social media account, or acting as an appointed representative at an online or offline event.

like this

**Comment by elle-Bee** [comment]
Hey @pinak22dhir amazing code of conduct 😂. Go ahead!

**Comment by pinak22dhir** [comment]
you want to share your mail id

**Comment by elle-Bee** [comment]
Can you just redirect them to the telegram group: https://t.me/+__4-ipvNiw0yNTY1

**Comment by pinak22dhir** [comment]
@elle-Bee  add kwoc tag on the issue
